plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'com.google.devtools.ksp'
    id 'org.jetbrains.kotlin.plugin.compose' version '2.0.0'
}

android {
    namespace 'com.example.autosim'
    compileSdk 36

    defaultConfig {
        applicationId "com.example.autosim"
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName "0.1"
    }

    kotlinOptions {
        jvmTarget = '11'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    packagingOptions {
        resources {
            excludes += ['/META-INF/AL2.0', '/META-INF/LGPL2.1']
        }
    }
}

dependencies {
    implementation platform('androidx.compose:compose-bom:2025.11.00')
    implementation 'androidx.activity:activity-compose:1.11.0'
    implementation 'androidx.compose.material3:material3'
    implementation 'androidx.compose.material:material-icons-extended'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'androidx.compose.ui:ui-tooling-preview'
    debugImplementation 'androidx.compose.ui:ui-tooling'
    implementation 'androidx.navigation:navigation-compose:2.9.6'

    implementation 'androidx.core:core-ktx:1.17.0'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.9.4'
    implementation 'androidx.lifecycle:lifecycle-service:2.9.4'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.10.2'

    // Room
    implementation 'androidx.room:room-runtime:2.6.1'
    implementation 'androidx.room:room-ktx:2.6.1'
    ksp 'androidx.room:room-compiler:2.6.1'

    // ML Kit
    implementation 'com.google.mlkit:text-recognition:16.0.1'

    // Gson for JSON
    implementation 'com.google.code.gson:gson:2.10.1'
}
